### ISSUE TITLE
renv.lock - MASS_7.3-61.tar.gz

### ISSUE THREAD

**Issue by ericaVoss** [ohdsi-studies/StrategusStudyRepoTemplate#6]
https://github.com/ohdsi-studies/StrategusStudyRepoTemplate/blob/main/renv.lock#L148-L152

Does this exist?
MASS_7.3-61.tar.gz

https://cloud.r-project.org/src/contrib/Archive/MASS/

```text
- Downloading MASS from CRAN ...                	ERROR [error code 22]
Warning: failed to find binary for 'MASS 7.3-61' in package repositories
Warning: failed to find source for 'MASS 7.3-61' in package repositories
Warning: error downloading 'https://cloud.r-project.org/src/contrib/Archive/MASS/MASS_7.3-61.tar.gz' [error code 22]
```

**Comment by anthonysena** [comment]
Closing this out since it was resolved by moving to the latest version of R. Thanks for reporting it @ericaVoss!
